// ============================================
// VisuAlg Web IDE - Exemplos prontos
// ============================================

(function () {
    'use strict';

    window.VisuAlgExamples = [
        {
            id: 'ola-mundo',
            title: 'Olá, mundo!',
            level: 'Primeiros passos',
            description: 'Execute seu primeiro algoritmo e veja uma mensagem no console.',
            source: [
                'Algoritmo "OlaMundo"',
                '',
                'Inicio',
                '  escreval("Olá, mundo!")',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'Olá, mundo!'
        },
        {
            id: 'media-escolar',
            title: 'Média escolar',
            level: 'Variáveis',
            description: 'Simule o fechamento das notas de um aluno e calcule sua média.',
            source: [
                'Algoritmo "MediaEscolar"',
                'Var',
                '  nota1, nota2, media: real',
                '',
                'Inicio',
                '  escreval("Professor, digite a primeira nota:")',
                '  leia(nota1)',
                '  escreval("Agora digite a segunda nota:")',
                '  leia(nota2)',
                '  media <- (nota1 + nota2) / 2',
                '  escreval("Média final: ", media:1:1)',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['8', '7.5'],
            expected: ['Professor, digite a primeira nota:', '8', 'Agora digite a segunda nota:', '7.5', 'Média final: 7.8'].join('\n')
        },
        {
            id: 'aprovacao',
            title: 'Aluno aprovado?',
            level: 'Condição',
            description: 'Consulte a situação de um aluno a partir da média informada.',
            source: [
                'Algoritmo "Aprovacao"',
                'Var',
                '  media: real',
                '',
                'Inicio',
                '  escreval("Digite a média do aluno:")',
                '  leia(media)',
                '  se media >= 7 entao',
                '    escreval("Aluno aprovado!")',
                '  senao',
                '    escreval("Aluno em recuperação.")',
                '  fimse',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['8.2'],
            expected: ['Digite a média do aluno:', '8.2', 'Aluno aprovado!'].join('\n')
        },
        {
            id: 'tabuada',
            title: 'Gerador de tabuada',
            level: 'Repetição',
            description: 'Peça um número ao estudante e monte a tabuada completa.',
            source: [
                'Algoritmo "Tabuada"',
                'Var',
                '  i, numero: inteiro',
                '',
                'Inicio',
                '  escreval("Qual tabuada você quer praticar?")',
                '  leia(numero)',
                '  para i de 1 ate 10 faca',
                '    escreval(numero, " x ", i, " = ", numero * i)',
                '  fimpara',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['7'],
            expected: [
                'Qual tabuada você quer praticar?',
                '7',
                '7 x 1 = 7',
                '7 x 2 = 14',
                '7 x 3 = 21',
                '7 x 4 = 28',
                '7 x 5 = 35',
                '7 x 6 = 42',
                '7 x 7 = 49',
                '7 x 8 = 56',
                '7 x 9 = 63',
                '7 x 10 = 70'
            ].join('\n')
        },
        {
            id: 'vetores',
            title: 'Soma de um vetor',
            level: 'Vetores',
            description: 'Preencha um vetor, percorra seus elementos e calcule uma soma.',
            source: [
                'Algoritmo "SomaVetor"',
                'Var',
                '  numeros: vetor [1..5] de inteiro',
                '  i, soma: inteiro',
                '',
                'Inicio',
                '  soma <- 0',
                '  para i de 1 ate 5 faca',
                '    numeros[i] <- i * i',
                '    soma <- soma + numeros[i]',
                '  fimpara',
                '  escreval("Soma dos quadrados: ", soma)',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'Soma dos quadrados: 55'
        },
        {
            id: 'operacoes-aritmeticas',
            title: 'Operações aritméticas',
            level: 'Variáveis',
            description: 'Calcule soma, diferença, produto e quociente com duas variáveis.',
            source: [
                'Algoritmo "OperacoesAritmeticas"',
                'Var',
                '  a, b: inteiro',
                '',
                'Inicio',
                '  a <- 12',
                '  b <- 4',
                '  escreval("Soma: ", a + b)',
                '  escreval("Diferença: ", a - b)',
                '  escreval("Produto: ", a * b)',
                '  escreval("Quociente: ", a / b)',
                'fimalgoritmo'
            ].join('\n'),
            expected: ['Soma: 16', 'Diferença: 8', 'Produto: 48', 'Quociente: 3'].join('\n')
        },
        {
            id: 'divisao-inteira-resto',
            title: 'Divisão inteira e resto',
            level: 'Operadores',
            description: 'Conheça os operadores div e mod em uma divisão inteira.',
            source: [
                'Algoritmo "DivisaoInteira"',
                'Var',
                '  dividendo, divisor: inteiro',
                '',
                'Inicio',
                '  dividendo <- 29',
                '  divisor <- 5',
                '  escreval("Quociente: ", dividendo div divisor)',
                '  escreval("Resto: ", dividendo mod divisor)',
                'fimalgoritmo'
            ].join('\n'),
            expected: ['Quociente: 5', 'Resto: 4'].join('\n')
        },
        {
            id: 'troca-valores',
            title: 'Troca de valores',
            level: 'Variáveis',
            description: 'Troque os conteúdos de duas variáveis usando uma variável auxiliar.',
            source: [
                'Algoritmo "TrocaValores"',
                'Var',
                '  a, b, auxiliar: inteiro',
                '',
                'Inicio',
                '  a <- 10',
                '  b <- 25',
                '  auxiliar <- a',
                '  a <- b',
                '  b <- auxiliar',
                '  escreval("a = ", a, ", b = ", b)',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'a = 25, b = 10'
        },
        {
            id: 'par-ou-impar',
            title: 'Par ou ímpar',
            level: 'Condição',
            description: 'Receba um número do usuário e descubra se ele é par ou ímpar.',
            source: [
                'Algoritmo "ParOuImpar"',
                'Var',
                '  numero: inteiro',
                '',
                'Inicio',
                '  escreval("Digite um número inteiro para analisar:")',
                '  leia(numero)',
                '  se numero mod 2 = 0 entao',
                '    escreval(numero, " é par.")',
                '  senao',
                '    escreval(numero, " é ímpar.")',
                '  fimse',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['42'],
            expected: ['Digite um número inteiro para analisar:', '42', '42 é par.'].join('\n')
        },
        {
            id: 'maior-de-tres',
            title: 'Maior de três números',
            level: 'Condição',
            description: 'Combine comparações para encontrar o maior entre três valores.',
            source: [
                'Algoritmo "MaiorDeTres"',
                'Var',
                '  a, b, c, maior: inteiro',
                '',
                'Inicio',
                '  a <- 18',
                '  b <- 31',
                '  c <- 24',
                '  maior <- a',
                '  se b > maior entao',
                '    maior <- b',
                '  fimse',
                '  se c > maior entao',
                '    maior <- c',
                '  fimse',
                '  escreval("Maior: ", maior)',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'Maior: 31'
        },
        {
            id: 'classificacao-idade',
            title: 'Classificação por idade',
            level: 'Condição',
            description: 'Simule a classificação etária de um visitante de um evento.',
            source: [
                'Algoritmo "ClassificacaoIdade"',
                'Var',
                '  idade: inteiro',
                '',
                'Inicio',
                '  escreval("Bem-vindo ao evento! Qual é a sua idade?")',
                '  leia(idade)',
                '  se idade < 12 entao',
                '    escreval("Criança")',
                '  senao se idade < 18 entao',
                '    escreval("Adolescente")',
                '  senao',
                '    escreval("Adulto")',
                '  fimse',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['16'],
            expected: ['Bem-vindo ao evento! Qual é a sua idade?', '16', 'Adolescente'].join('\n')
        },
        {
            id: 'ano-bissexto',
            title: 'Ano bissexto',
            level: 'Operadores lógicos',
            description: 'Combine e, ou e mod para aplicar a regra do calendário gregoriano.',
            source: [
                'Algoritmo "AnoBissexto"',
                'Var',
                '  ano: inteiro',
                '',
                'Inicio',
                '  ano <- 2024',
                '  se (ano mod 400 = 0) ou ((ano mod 4 = 0) e (ano mod 100 <> 0)) entao',
                '    escreval(ano, " é bissexto.")',
                '  senao',
                '    escreval(ano, " não é bissexto.")',
                '  fimse',
                'fimalgoritmo'
            ].join('\n'),
            expected: '2024 é bissexto.'
        },
        {
            id: 'tipo-triangulo',
            title: 'Tipo de triângulo',
            level: 'Condição',
            description: 'Ajude uma oficina de geometria a classificar três medidas.',
            source: [
                'Algoritmo "TipoTriangulo"',
                'Var',
                '  a, b, c: real',
                '',
                'Inicio',
                '  escreval("Informe o primeiro lado do triângulo:")',
                '  leia(a)',
                '  escreval("Informe o segundo lado:")',
                '  leia(b)',
                '  escreval("Informe o terceiro lado:")',
                '  leia(c)',
                '  se (a + b > c) e (a + c > b) e (b + c > a) entao',
                '    se (a = b) e (b = c) entao',
                '      escreval("Equilátero")',
                '    senao se (a = b) ou (a = c) ou (b = c) entao',
                '      escreval("Isósceles")',
                '    senao',
                '      escreval("Escaleno")',
                '    fimse',
                '  senao',
                '    escreval("Não forma um triângulo")',
                '  fimse',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['5', '5', '8'],
            expected: [
                'Informe o primeiro lado do triângulo:',
                '5',
                'Informe o segundo lado:',
                '5',
                'Informe o terceiro lado:',
                '8',
                'Isósceles'
            ].join('\n')
        },
        {
            id: 'menu-escolha',
            title: 'Menu com escolha',
            level: 'Seleção',
            description: 'Mostre o menu de uma biblioteca e execute a opção escolhida.',
            source: [
                'Algoritmo "MenuEscolha"',
                'Var',
                '  opcao: inteiro',
                '',
                'Inicio',
                '  escreval("=== Biblioteca comunitária ===")',
                '  escreval("1 - Cadastrar livro")',
                '  escreval("2 - Consultar catálogo")',
                '  escreval("3 - Sair")',
                '  escreval("Digite a opção desejada:")',
                '  leia(opcao)',
                '  escolha opcao',
                '    caso 1',
                '      escreval("Cadastrar")',
                '    caso 2',
                '      escreval("Consultar")',
                '    caso 3',
                '      escreval("Sair")',
                '    outrocaso',
                '      escreval("Opção inválida")',
                '  fimescolha',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['2'],
            expected: [
                '=== Biblioteca comunitária ===',
                '1 - Cadastrar livro',
                '2 - Consultar catálogo',
                '3 - Sair',
                'Digite a opção desejada:',
                '2',
                'Consultar'
            ].join('\n')
        },
        {
            id: 'contagem-regressiva',
            title: 'Contagem regressiva',
            level: 'Repetição',
            description: 'Controle uma contagem regressiva com enquanto.',
            source: [
                'Algoritmo "ContagemRegressiva"',
                'Var',
                '  numero: inteiro',
                '',
                'Inicio',
                '  numero <- 5',
                '  enquanto numero >= 1 faca',
                '    escreval(numero)',
                '    numero <- numero - 1',
                '  fimenquanto',
                '  escreval("Já!")',
                'fimalgoritmo'
            ].join('\n'),
            expected: ['5', '4', '3', '2', '1', 'Já!'].join('\n')
        },
        {
            id: 'repita-ate',
            title: 'Repita até',
            level: 'Repetição',
            description: 'Execute um bloco ao menos uma vez usando repita e até.',
            source: [
                'Algoritmo "RepitaAte"',
                'Var',
                '  contador: inteiro',
                '',
                'Inicio',
                '  contador <- 1',
                '  repita',
                '    escreval("Passo ", contador)',
                '    contador <- contador + 1',
                '  ate contador > 3',
                'fimalgoritmo'
            ].join('\n'),
            expected: ['Passo 1', 'Passo 2', 'Passo 3'].join('\n')
        },
        {
            id: 'soma-pares',
            title: 'Soma dos pares',
            level: 'Repetição',
            description: 'Use passo para percorrer apenas números pares.',
            source: [
                'Algoritmo "SomaPares"',
                'Var',
                '  numero, soma: inteiro',
                '',
                'Inicio',
                '  soma <- 0',
                '  para numero de 2 ate 10 passo 2 faca',
                '    soma <- soma + numero',
                '  fimpara',
                '  escreval("Soma: ", soma)',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'Soma: 30'
        },
        {
            id: 'fatorial-iterativo',
            title: 'Fatorial iterativo',
            level: 'Repetição',
            description: 'Receba um número e calcule seu fatorial acumulando produtos.',
            source: [
                'Algoritmo "FatorialIterativo"',
                'Var',
                '  numero, i, fatorial: inteiro',
                '',
                'Inicio',
                '  escreval("Digite um número para calcular o fatorial:")',
                '  leia(numero)',
                '  fatorial <- 1',
                '  para i de 2 ate numero faca',
                '    fatorial <- fatorial * i',
                '  fimpara',
                '  escreval(numero, "! = ", fatorial)',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['6'],
            expected: ['Digite um número para calcular o fatorial:', '6', '6! = 720'].join('\n')
        },
        {
            id: 'sequencia-fibonacci',
            title: 'Sequência de Fibonacci',
            level: 'Repetição',
            description: 'Gere termos de Fibonacci atualizando duas variáveis.',
            source: [
                'Algoritmo "Fibonacci"',
                'Var',
                '  i, atual, proximo, auxiliar: inteiro',
                '',
                'Inicio',
                '  atual <- 0',
                '  proximo <- 1',
                '  para i de 1 ate 8 faca',
                '    escreval(atual)',
                '    auxiliar <- atual + proximo',
                '    atual <- proximo',
                '    proximo <- auxiliar',
                '  fimpara',
                'fimalgoritmo'
            ].join('\n'),
            expected: ['0', '1', '1', '2', '3', '5', '8', '13'].join('\n')
        },
        {
            id: 'numero-primo',
            title: 'Número primo',
            level: 'Repetição',
            description: 'Analise o número informado por um participante de um desafio matemático.',
            source: [
                'Algoritmo "NumeroPrimo"',
                'Var',
                '  numero, divisor, quantidade: inteiro',
                '',
                'Inicio',
                '  escreval("Desafio dos primos: digite um número positivo:")',
                '  leia(numero)',
                '  quantidade <- 0',
                '  para divisor de 1 ate numero faca',
                '    se numero mod divisor = 0 entao',
                '      quantidade <- quantidade + 1',
                '    fimse',
                '  fimpara',
                '  se quantidade = 2 entao',
                '    escreval(numero, " é primo.")',
                '  senao',
                '    escreval(numero, " não é primo.")',
                '  fimse',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['17'],
            expected: ['Desafio dos primos: digite um número positivo:', '17', '17 é primo.'].join('\n')
        },
        {
            id: 'mdc-euclides',
            title: 'MDC pelo algoritmo de Euclides',
            level: 'Repetição',
            description: 'Encontre o máximo divisor comum com divisões sucessivas.',
            source: [
                'Algoritmo "MdcEuclides"',
                'Var',
                '  a, b, resto: inteiro',
                '',
                'Inicio',
                '  a <- 84',
                '  b <- 30',
                '  enquanto b <> 0 faca',
                '    resto <- a mod b',
                '    a <- b',
                '    b <- resto',
                '  fimenquanto',
                '  escreval("MDC: ", a)',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'MDC: 6'
        },
        {
            id: 'maior-no-vetor',
            title: 'Maior valor do vetor',
            level: 'Vetores',
            description: 'Percorra um vetor para localizar seu maior elemento.',
            source: [
                'Algoritmo "MaiorNoVetor"',
                'Var',
                '  valores: vetor [1..6] de inteiro',
                '  i, maior: inteiro',
                '',
                'Inicio',
                '  valores[1] <- 12',
                '  valores[2] <- 7',
                '  valores[3] <- 35',
                '  valores[4] <- 19',
                '  valores[5] <- 28',
                '  valores[6] <- 4',
                '  maior <- valores[1]',
                '  para i de 2 ate 6 faca',
                '    se valores[i] > maior entao',
                '      maior <- valores[i]',
                '    fimse',
                '  fimpara',
                '  escreval("Maior valor: ", maior)',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'Maior valor: 35'
        },
        {
            id: 'vetor-invertido',
            title: 'Vetor em ordem inversa',
            level: 'Vetores',
            description: 'Leia conceitualmente um vetor do último elemento para o primeiro.',
            source: [
                'Algoritmo "VetorInvertido"',
                'Var',
                '  letras: vetor [1..5] de caractere',
                '  i: inteiro',
                '',
                'Inicio',
                '  letras[1] <- "A"',
                '  letras[2] <- "B"',
                '  letras[3] <- "C"',
                '  letras[4] <- "D"',
                '  letras[5] <- "E"',
                '  para i de 5 ate 1 passo -1 faca',
                '    escreva(letras[i])',
                '  fimpara',
                '  escreval()',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'EDCBA'
        },
        {
            id: 'media-do-vetor',
            title: 'Média de um vetor',
            level: 'Vetores',
            description: 'Some valores reais armazenados e calcule a média do conjunto.',
            source: [
                'Algoritmo "MediaVetor"',
                'Var',
                '  notas: vetor [1..4] de real',
                '  i: inteiro',
                '  soma, media: real',
                '',
                'Inicio',
                '  notas[1] <- 6.5',
                '  notas[2] <- 8',
                '  notas[3] <- 7.5',
                '  notas[4] <- 9',
                '  soma <- 0',
                '  para i de 1 ate 4 faca',
                '    soma <- soma + notas[i]',
                '  fimpara',
                '  media <- soma / 4',
                '  escreval("Média: ", media:1:2)',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'Média: 7.75'
        },
        {
            id: 'ordenacao-bolha',
            title: 'Ordenação por bolha',
            level: 'Vetores',
            description: 'Ordene um pequeno vetor usando comparações e trocas sucessivas.',
            source: [
                'Algoritmo "OrdenacaoBolha"',
                'Var',
                '  valores: vetor [1..5] de inteiro',
                '  i, j, auxiliar: inteiro',
                '',
                'Inicio',
                '  valores[1] <- 5',
                '  valores[2] <- 1',
                '  valores[3] <- 4',
                '  valores[4] <- 2',
                '  valores[5] <- 3',
                '  para i de 1 ate 4 faca',
                '    para j de 1 ate 5 - i faca',
                '      se valores[j] > valores[j + 1] entao',
                '        auxiliar <- valores[j]',
                '        valores[j] <- valores[j + 1]',
                '        valores[j + 1] <- auxiliar',
                '      fimse',
                '    fimpara',
                '  fimpara',
                '  para i de 1 ate 5 faca',
                '    escreva(valores[i])',
                '  fimpara',
                '  escreval()',
                'fimalgoritmo'
            ].join('\n'),
            expected: '12345'
        },
        {
            id: 'diagonal-matriz',
            title: 'Diagonal de uma matriz',
            level: 'Matrizes',
            description: 'Preencha uma matriz bidimensional e some sua diagonal principal.',
            source: [
                'Algoritmo "DiagonalMatriz"',
                'Var',
                '  matriz: vetor [1..3, 1..3] de inteiro',
                '  i, j, soma: inteiro',
                '',
                'Inicio',
                '  para i de 1 ate 3 faca',
                '    para j de 1 ate 3 faca',
                '      matriz[i, j] <- i + j',
                '    fimpara',
                '  fimpara',
                '  soma <- 0',
                '  para i de 1 ate 3 faca',
                '    soma <- soma + matriz[i, i]',
                '  fimpara',
                '  escreval("Soma da diagonal: ", soma)',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'Soma da diagonal: 12'
        },
        {
            id: 'manipulacao-texto',
            title: 'Maiúsculas e minúsculas',
            level: 'Textos',
            description: 'Transforme um texto com as funções maiusc e minusc.',
            source: [
                'Algoritmo "ManipulacaoTexto"',
                'Var',
                '  palavra: caractere',
                '',
                'Inicio',
                '  palavra <- "Algoritmo"',
                '  escreval(maiusc(palavra))',
                '  escreval(minusc(palavra))',
                'fimalgoritmo'
            ].join('\n'),
            expected: ['ALGORITMO', 'algoritmo'].join('\n')
        },
        {
            id: 'recorte-texto',
            title: 'Recorte de texto',
            level: 'Textos',
            description: 'Extraia uma parte de uma cadeia com a função copia.',
            source: [
                'Algoritmo "RecorteTexto"',
                'Var',
                '  linguagem: caractere',
                '',
                'Inicio',
                '  linguagem <- "Portugol"',
                '  escreval("Trecho: ", copia(linguagem, 1, 5))',
                '  escreval("Tamanho: ", compr(linguagem))',
                'fimalgoritmo'
            ].join('\n'),
            expected: ['Trecho: Portu', 'Tamanho: 8'].join('\n')
        },
        {
            id: 'busca-em-texto',
            title: 'Busca em texto',
            level: 'Textos',
            description: 'Encontre a posição inicial de uma palavra dentro de uma frase.',
            source: [
                'Algoritmo "BuscaTexto"',
                'Var',
                '  frase: caractere',
                '',
                'Inicio',
                '  frase <- "Aprender algoritmos"',
                '  escreval("Posição: ", pos("algoritmos", frase))',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'Posição: 10'
        },
        {
            id: 'funcoes-matematicas',
            title: 'Funções matemáticas',
            level: 'Matemática',
            description: 'Use funções nativas para valor absoluto, potência e raiz quadrada.',
            source: [
                'Algoritmo "FuncoesMatematicas"',
                '',
                'Inicio',
                '  escreval("Absoluto: ", abs(-15))',
                '  escreval("Quadrado: ", quad(6))',
                '  escreval("Raiz: ", raizq(81))',
                '  escreval("Potência: ", exp(2, 5))',
                'fimalgoritmo'
            ].join('\n'),
            expected: ['Absoluto: 15', 'Quadrado: 36', 'Raiz: 9', 'Potência: 32'].join('\n')
        },
        {
            id: 'conversao-temperatura',
            title: 'Conversão de temperatura',
            level: 'Fórmulas',
            description: 'Ajude um viajante a converter a temperatura local para Fahrenheit.',
            source: [
                'Algoritmo "ConversaoTemperatura"',
                'Var',
                '  celsius, fahrenheit: real',
                '',
                'Inicio',
                '  escreval("Viajante, qual é a temperatura em Celsius?")',
                '  leia(celsius)',
                '  fahrenheit <- celsius * 9 / 5 + 32',
                '  escreval(celsius:1:1, " °C = ", fahrenheit:1:1, " °F")',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['25'],
            expected: ['Viajante, qual é a temperatura em Celsius?', '25', '25.0 °C = 77.0 °F'].join('\n')
        },
        {
            id: 'juros-compostos',
            title: 'Juros compostos',
            level: 'Fórmulas',
            description: 'Simule um investimento com capital, taxa mensal e prazo informados.',
            source: [
                'Algoritmo "JurosCompostos"',
                'Var',
                '  capital, taxa, montante: real',
                '  meses: inteiro',
                '',
                'Inicio',
                '  escreval("=== Simulador de investimento ===")',
                '  escreval("Informe o capital inicial:")',
                '  leia(capital)',
                '  escreval("Informe a taxa mensal em decimal (ex.: 0.02):")',
                '  leia(taxa)',
                '  escreval("Por quantos meses o dinheiro ficará investido?")',
                '  leia(meses)',
                '  montante <- capital * (1 + taxa) ^ meses',
                '  escreval("Montante: R$ ", montante:1:2)',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['1000', '0.02', '6'],
            expected: [
                '=== Simulador de investimento ===',
                'Informe o capital inicial:',
                '1000',
                'Informe a taxa mensal em decimal (ex.: 0.02):',
                '0.02',
                'Por quantos meses o dinheiro ficará investido?',
                '6',
                'Montante: R$ 1126.16'
            ].join('\n')
        },
        {
            id: 'procedimento-saudacao',
            title: 'Procedimento com parâmetro',
            level: 'Procedimentos',
            description: 'Pergunte o nome de um visitante e use um procedimento para recebê-lo.',
            source: [
                'Algoritmo "ProcedimentoSaudacao"',
                'Var',
                '  visitante: caractere',
                '',
                'procedimento saudar(nome: caractere)',
                'inicio',
                '  escreval("Olá, ", nome, "!")',
                'fimprocedimento',
                '',
                'Inicio',
                '  escreval("Olá! Como você se chama?")',
                '  leia(visitante)',
                '  saudar(visitante)',
                'fimalgoritmo'
            ].join('\n'),
            inputs: ['Marina'],
            expected: ['Olá! Como você se chama?', 'Marina', 'Olá, Marina!'].join('\n')
        },
        {
            id: 'procedimento-referencia',
            title: 'Parâmetro por referência',
            level: 'Procedimentos',
            description: 'Altere uma variável externa usando um parâmetro declarado com var.',
            source: [
                'Algoritmo "ProcedimentoReferencia"',
                'Var',
                '  numero: inteiro',
                '',
                'procedimento incrementar(var valor: inteiro)',
                'inicio',
                '  valor <- valor + 1',
                'fimprocedimento',
                '',
                'Inicio',
                '  numero <- 9',
                '  incrementar(numero)',
                '  escreval("Resultado: ", numero)',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'Resultado: 10'
        },
        {
            id: 'funcao-dobro',
            title: 'Função com retorno',
            level: 'Funções',
            description: 'Crie uma função que calcula e retorna o dobro de um valor.',
            source: [
                'Algoritmo "FuncaoDobro"',
                'Var',
                '  resultado: inteiro',
                '',
                'funcao dobro(valor: inteiro): inteiro',
                'inicio',
                '  retorne valor * 2',
                'fimfuncao',
                '',
                'Inicio',
                '  resultado <- dobro(21)',
                '  escreval("Dobro: ", resultado)',
                'fimalgoritmo'
            ].join('\n'),
            expected: 'Dobro: 42'
        },
        {
            id: 'fatorial-recursivo',
            title: 'Fatorial recursivo',
            level: 'Funções',
            description: 'Resolva o fatorial com uma função que chama a si mesma.',
            source: [
                'Algoritmo "FatorialRecursivo"',
                '',
                'funcao fatorial(numero: inteiro): inteiro',
                'inicio',
                '  se numero <= 1 entao',
                '    retorne 1',
                '  senao',
                '    retorne numero * fatorial(numero - 1)',
                '  fimse',
                'fimfuncao',
                '',
                'Inicio',
                '  escreval("5! = ", fatorial(5))',
                'fimalgoritmo'
            ].join('\n'),
            expected: '5! = 120'
        },
        {
            id: 'conversao-texto-numero',
            title: 'Conversão entre texto e número',
            level: 'Conversões',
            description: 'Converta uma cadeia numérica e transforme o resultado em texto novamente.',
            source: [
                'Algoritmo "ConversaoTextoNumero"',
                'Var',
                '  numero: real',
                '  texto: caractere',
                '',
                'Inicio',
                '  numero <- caracpnum("12,5")',
                '  numero <- numero * 2',
                '  texto <- numpcarac(numero)',
                '  escreval("Número: ", numero:1:1)',
                '  escreval("Texto: ", texto)',
                'fimalgoritmo'
            ].join('\n'),
            expected: ['Número: 25.0', 'Texto: 25'].join('\n')
        }
    ];
})();
